use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :skaro, SkaroWeb.Endpoint,
  http: [:inet6, port: "${PORT}"],
  url: [host: "${HOST}", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  root: "."

# Do not print debug messages in production
config :logger, level: :info

config :sentry,
  dsn: "${SENTRY_DSN}",
  environment_name: :prod,
  enable_source_code_context: true,
  root_source_code_path: File.cwd!(),
  tags: %{
    env: "production"
  }

config :skaro, Skaro.Repo,
  username: "${POSTGRES_USER}",
  password: "${POSTGRES_PASSWORD}",
  database: "skaro_production",
  hostname: "${POSTGRES_HOST}",
  pool_size: 10
